dist: xenial
language: python

services:
  - redis-server
  - docker

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - echo "skipping tests"

deploy:
  - provider: script
    script: bash ./docker-deploy.sh master
    on:
      branch: master

  - provider: script
    script: bash ./docker-deploy.sh dev
    on:
      branch: dev
